# Generated by Django 4.2.1 on 2023-05-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_products_alter_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='processing', max_length=20),
        ),
    ]
